apiVersion: "rancher.com/v1"
kind: Logging
metadata:
  name: clusterlogging
  namespace: ns-1
target: 
  output_type: elasticsearch
  output_host: 192.168.33.176
  output_port: 9200
  output_logstash_prefix: "logstash"
  output_logstash_dateformat: '%Y-%m-%d %H:%M:%S'
  output_tag_key: "mytag3"